const { EmbedBuilder, MessageFlags } = require("discord.js");

const INCIDENT_TYPES = [
    "raid", "spam", "link", "mention", "bot", "role",
    "channel", "permission", "moderation", "security",
    "coordinated", "admin_abuse", "mass_action"
];

const STATUS = {
    ACTIVE: "active",
    REVIEW: "review",
    RESOLVED: "resolved",
    FALSE_POSITIVE: "false_positive"
};

const STATUS_LABELS = {
    active: "🔴 Activo",
    review: "🟡 En revisión",
    resolved: "🟢 Resuelto",
    false_positive: "⚪ Falso positivo"
};

const TYPE_LABELS = {
    raid: "⚔️ Raid",
    spam: "📨 Spam",
    link: "🔗 Link",
    mention: "📣 Mención",
    bot: "🤖 Bot",
    role: "🎭 Rol",
    channel: "📁 Canal",
    permission: "🔐 Permiso",
    moderation: "🔨 Moderación",
    security: "🛡️ Seguridad",
    coordinated: "🕵️ Coordinado",
    admin_abuse: "⚠️ Abuso admin",
    mass_action: "💥 Acción masiva"
};

function ensureIncidentConfig(gc) {
    if (!gc.aiControl) gc.aiControl = {};
    if (!gc.aiControl.incidents) gc.aiControl.incidents = [];
    if (typeof gc.aiControl.incidentSeq !== "number") gc.aiControl.incidentSeq = 0;
    if (!gc.aiControl.daily) gc.aiControl.daily = {};
    if (!gc.aiControl.stats) {
        gc.aiControl.stats = {
            incidentsToday: 0,
            incidentsWeek: 0,
            incidentsMonth: 0,
            raidsDetected: 0,
            spamBlocked: 0,
            linksBlocked: 0,
            mentionsBlocked: 0,
            quarantines: 0,
            autoActions: 0,
            restorations: 0
        };
    }
    return gc;
}

function generateIncidentId(gc) {
    gc.aiControl.incidentSeq = (gc.aiControl.incidentSeq || 0) + 1;
    const seq = String(gc.aiControl.incidentSeq).padStart(4, "0");
    const now = new Date();
    const y = now.getFullYear();
    const m = String(now.getMonth() + 1).padStart(2, "0");
    const d = String(now.getDate()).padStart(2, "0");
    return `INC-${y}-${m}${d}-${seq}`;
}

function recordIncident(gc, data) {
    ensureIncidentConfig(gc);
    const incident = {
        id: generateIncidentId(gc),
        type: data.type || "security",
        userId: data.userId || null,
        userName: data.userName || null,
        userTag: data.userTag || null,
        riskScore: data.riskScore || 0,
        timestamp: Date.now(),
        system: data.system || "aiControl",
        action: data.action || "log",
        evidence: data.evidence || [],
        status: STATUS.ACTIVE,
        resolvedBy: null,
        resolvedAt: null,
        description: data.description || "",
        autoGenerated: data.autoGenerated !== false
    };
    gc.aiControl.incidents.unshift(incident);

    const today = new Date().toISOString().slice(0, 10);
    if (!gc.aiControl.daily[today]) gc.aiControl.daily[today] = { incidents: 0 };
    gc.aiControl.daily[today].incidents = (gc.aiControl.daily[today].incidents || 0) + 1;

    gc.aiControl.stats.incidentsToday = (gc.aiControl.stats.incidentsToday || 0) + 1;

    const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);
    if (today >= weekAgo) gc.aiControl.stats.incidentsWeek = (gc.aiControl.stats.incidentsWeek || 0) + 1;

    const monthAgo = new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10);
    if (today >= monthAgo) gc.aiControl.stats.incidentsMonth = (gc.aiControl.stats.incidentsMonth || 0) + 1;

    if (incident.type === "raid") gc.aiControl.stats.raidsDetected = (gc.aiControl.stats.raidsDetected || 0) + 1;
    if (incident.type === "spam") gc.aiControl.stats.spamBlocked = (gc.aiControl.stats.spamBlocked || 0) + 1;
    if (incident.type === "link") gc.aiControl.stats.linksBlocked = (gc.aiControl.stats.linksBlocked || 0) + 1;
    if (incident.type === "mention") gc.aiControl.stats.mentionsBlocked = (gc.aiControl.stats.mentionsBlocked || 0) + 1;
    if (incident.action === "quarantine") gc.aiControl.stats.quarantines = (gc.aiControl.stats.quarantines || 0) + 1;
    if (incident.autoGenerated) gc.aiControl.stats.autoActions = (gc.aiControl.stats.autoActions || 0) + 1;

    console.log(`[AI:INCIDENT] id=${incident.id} type=${incident.type} user=${incident.userName || incident.userId} risk=${incident.riskScore} action=${incident.action}`);
    return incident;
}

function getIncidents(gc, opts = {}) {
    ensureIncidentConfig(gc);
    let list = gc.aiControl.incidents || [];
    if (opts.type) list = list.filter(i => i.type === opts.type);
    if (opts.status) list = list.filter(i => i.status === opts.status);
    if (opts.userId) list = list.filter(i => i.userId === opts.userId);
    if (opts.days) {
        const cutoff = Date.now() - opts.days * 86400000;
        list = list.filter(i => i.timestamp >= cutoff);
    }
    return list;
}

function getIncidentById(gc, id) {
    ensureIncidentConfig(gc);
    return (gc.aiControl.incidents || []).find(i => i.id === id) || null;
}

function updateIncidentStatus(gc, id, status, resolvedBy) {
    const incident = getIncidentById(gc, id);
    if (!incident) return null;
    incident.status = status;
    if (status === STATUS.RESOLVED || status === STATUS.FALSE_POSITIVE) {
        incident.resolvedBy = resolvedBy;
        incident.resolvedAt = Date.now();
    }
    console.log(`[AI:INCIDENT] id=${id} status=${status} by=${resolvedBy}`);
    return incident;
}

function getDailyStats(gc, days = 30) {
    ensureIncidentConfig(gc);
    const result = {};
    for (let i = 0; i < days; i++) {
        const d = new Date(Date.now() - i * 86400000).toISOString().slice(0, 10);
        result[d] = gc.aiControl.daily[d] || { incidents: 0 };
    }
    return result;
}

function getTypeBreakdown(gc, days = 30) {
    const incidents = getIncidents(gc, { days });
    const breakdown = {};
    for (const type of INCIDENT_TYPES) {
        breakdown[type] = incidents.filter(i => i.type === type).length;
    }
    return breakdown;
}

function getRecentIncidents(gc, count = 5) {
    ensureIncidentConfig(gc);
    return (gc.aiControl.incidents || []).slice(0, count);
}

function formatIncidentEmbed(incident) {
    const riskEmoji = incident.riskScore >= 81 ? "🔴" :
        incident.riskScore >= 61 ? "🟠" :
        incident.riskScore >= 31 ? "🟡" : "🟢";

    return new EmbedBuilder()
        .setColor(incident.riskScore >= 81 ? "#ED4245" :
            incident.riskScore >= 61 ? "#F47B67" :
            incident.riskScore >= 31 ? "#FEE75C" : "#57F287")
        .setTitle(`🚨 ${incident.id}`)
        .addFields(
            { name: "Tipo", value: TYPE_LABELS[incident.type] || incident.type, inline: true },
            { name: "Riesgo", value: `${riskEmoji} ${incident.riskScore}/100`, inline: true },
            { name: "Estado", value: STATUS_LABELS[incident.status] || incident.status, inline: true },
            { name: "Usuario", value: incident.userName ? `${incident.userName} (${incident.userId})` : (incident.userId || "N/A"), inline: true },
            { name: "Sistema", value: incident.system, inline: true },
            { name: "Acción", value: incident.action, inline: true },
            { name: "Descripción", value: incident.description || "Sin descripción", inline: false }
        )
        .setTimestamp(incident.timestamp)
        .setFooter({ text: incident.id });
}

function cleanOldIncidents(gc, retentionDays = 30) {
    ensureIncidentConfig(gc);
    const cutoff = Date.now() - retentionDays * 86400000;
    const before = gc.aiControl.incidents.length;
    gc.aiControl.incidents = gc.aiControl.incidents.filter(i => i.timestamp >= cutoff);
    return before - gc.aiControl.incidents.length;
}

function getStats(gc) {
    ensureIncidentConfig(gc);
    return gc.aiControl.stats;
}

function incrementStat(gc, key, amount = 1) {
    ensureIncidentConfig(gc);
    if (!gc.aiControl.stats) gc.aiControl.stats = {};
    gc.aiControl.stats[key] = (gc.aiControl.stats[key] || 0) + amount;
}

module.exports = {
    INCIDENT_TYPES,
    STATUS,
    STATUS_LABELS,
    TYPE_LABELS,
    ensureIncidentConfig,
    recordIncident,
    getIncidents,
    getIncidentById,
    updateIncidentStatus,
    getDailyStats,
    getTypeBreakdown,
    getRecentIncidents,
    formatIncidentEmbed,
    cleanOldIncidents,
    getStats,
    incrementStat
};
